"""Insert a generic /support/asset/<slug> route into web_app.py.

The route lets the support page link to the freshly-built PDFs and MP3s
under docs/ without one route handler per file. Whitelisted slugs only
(no directory traversal). Falls back to the existing inline-markdown PDF
route for the old user-guide URL so any externally-shared link keeps
working.

Pattern A from CLAUDE.md: byte-level replace on web_app.py because the
file is CRLF + has mojibake, and Edit corrupts Unicode dashes.
"""
from pathlib import Path

WEB = Path(r"C:\Users\USER\Desktop\solar-pv-designer-lite\web_app.py")
data = WEB.read_bytes()

# Anchor: insert the new route AFTER the existing support_user_guide_pdf
# closing return, BEFORE the next top-level constant. The existing route
# ends with a return on the line that calls _render_pdf. We anchor on the
# line that follows it.
TARGET = b'        "SolarPro_User_Guide.pdf")\r\n\r\n\r\n_TUTORIAL_EMAIL_SETUP_MD'

NEW = (
    b'        "SolarPro_User_Guide.pdf")\r\n'
    b'\r\n'
    b'\r\n'
    b'# ---------------------------------------------------------------\r\n'
    b'# Generic asset download - serves the build script output PDFs\r\n'
    b'# and MP3 walkthroughs straight from docs/. Whitelisted slug map\r\n'
    b'# prevents path traversal. Added 2026-06-17 so the support page\r\n'
    b'# can surface the freshly-built tutorial collateral without a\r\n'
    b'# bespoke route per file.\r\n'
    b'# ---------------------------------------------------------------\r\n'
    b'_SUPPORT_ASSETS = {\r\n'
    b'    # PDF tutorials (regenerated by build_collateral_pdfs.py)\r\n'
    b'    "user-guide":       ("SolarPro_User_Guide.pdf",       "application/pdf"),\r\n'
    b'    "technical-guide":  ("SolarPro_Technical_Guide.pdf",  "application/pdf"),\r\n'
    b'    "portal-tutorial":  ("SolarPro_Portal_Tutorial.pdf",  "application/pdf"),\r\n'
    b'    "sales-pitch":      ("SolarPro_Sales_Pitch.pdf",      "application/pdf"),\r\n'
    b'    # Audio walkthroughs (edge-tts, en-US-AriaNeural / en-US-GuyNeural)\r\n'
    b'    "user-walkthrough": ("SolarPro_User_Walkthrough.mp3", "audio/mpeg"),\r\n'
    b'    "tech-walkthrough": ("SolarPro_Tech_Walkthrough.mp3", "audio/mpeg"),\r\n'
    b'}\r\n'
    b'\r\n'
    b'@app.route("/support/asset/<slug>")\r\n'
    b'@login_required\r\n'
    b'def support_asset(slug):\r\n'
    b'    """Serve a tutorial asset from the docs/ directory.\r\n'
    b'\r\n'
    b'    `slug` MUST appear in _SUPPORT_ASSETS - any other value 404s,\r\n'
    b'    so the route is safe against path traversal (no slash in the\r\n'
    b'    slug ever reaches the filesystem).\r\n'
    b'    """\r\n'
    b'    entry = _SUPPORT_ASSETS.get(slug)\r\n'
    b'    if not entry:\r\n'
    b'        abort(404)\r\n'
    b'    filename, mime = entry\r\n'
    b'    docs_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "docs")\r\n'
    b'    path = os.path.join(docs_dir, filename)\r\n'
    b'    if not os.path.isfile(path):\r\n'
    b'        abort(404)\r\n'
    b'    # as_attachment=False so the browser opens the PDF inline; the\r\n'
    b'    # template already exposes a separate "Download" link if needed.\r\n'
    b'    return send_file(path, mimetype=mime, as_attachment=False,\r\n'
    b'                     download_name=filename)\r\n'
    b'\r\n'
    b'\r\n'
    b'_TUTORIAL_EMAIL_SETUP_MD'
)

if TARGET not in data:
    raise SystemExit("anchor not found - web_app.py shape changed")

if b'def support_asset(slug):' in data:
    print("already patched, no-op")
else:
    data = data.replace(TARGET, NEW, 1)
    WEB.write_bytes(data)
    print(f"patched: {WEB} ({len(NEW) - len(TARGET)} bytes inserted)")
