"""Stage 2 Basic Price Schedule exports: Excel + PDF + Email.

Inject 3 new routes + 2 byte helpers right after boms_basic_prices().
"""
import sys

path = "web_app.py"
data = open(path, "rb").read()
orig_len = len(data)

# Find the anchor we used for boms_basic_prices (the "BOM item add / update /
# delete" comment) and inject after the boms_basic_prices function ends but
# before that comment. The function ends with the close of render_template().
# Easiest: inject just before the "BOM item add / update / delete" anchor again
# (after our Task #10 injection, before the next route).
anchor_text = b'BOM item add / update / delete'
if data.count(anchor_text) != 1:
    print(f"FAIL: anchor 'BOM item add / update / delete' (got {data.count(anchor_text)})")
    sys.exit(1)

new_code = (
    b'# === Stage 2 exports (Task #11): Excel / PDF / Email for Basic Price Schedule ===\r\n'
    b'def _bom_basic_prices_compute(bom_id):\r\n'
    b'    """Shared helper: returns (bom, lines, grand_basic, cat_totals,\r\n'
    b'    currency, fx_rate). lines is a list of dicts with item, category,\r\n'
    b'    basic_price (local), qty, subtotal (local). NO mark-ups."""\r\n'
    b'    _ensure_bom_tables()\r\n'
    b'    uid = session["user_id"]\r\n'
    b'    bom = _bom_owned_or_404(bom_id, uid)\r\n'
    b'    items = _bom_items_with_prices(bom_id)\r\n'
    b'    _bcur = (bom["currency"] if "currency" in bom.keys() and bom["currency"] else "GHS")\r\n'
    b'    _brate = float(_CURRENCY_RATES_FROM_USD.get(_bcur, 1.0) or 1.0)\r\n'
    b'    lines = []\r\n'
    b'    grand_basic = 0.0\r\n'
    b'    cat_totals = {}\r\n'
    b'    for it in items:\r\n'
    b'        try:\r\n'
    b'            cat = (it["category_name"] if "category_name" in it.keys() else None) or "Uncategorised"\r\n'
    b'        except Exception:\r\n'
    b'            cat = "Uncategorised"\r\n'
    b'        basic_usd = float(\r\n'
    b'            (it["unit_price_override"] if it["unit_price_override"] is not None\r\n'
    b'             else (it["catalog_price"] or 0)) or 0\r\n'
    b'        )\r\n'
    b'        basic_local = basic_usd * _brate\r\n'
    b'        qty = float(it["qty"] or 0)\r\n'
    b'        subtotal = basic_local * qty\r\n'
    b'        grand_basic += subtotal\r\n'
    b'        cat_totals[cat] = cat_totals.get(cat, 0.0) + subtotal\r\n'
    b'        lines.append({\r\n'
    b'            "item": it, "category": cat,\r\n'
    b'            "basic_price": basic_local, "qty": qty, "subtotal": subtotal,\r\n'
    b'        })\r\n'
    b'    return bom, lines, grand_basic, cat_totals, _bcur, _brate\r\n'
    b'\r\n'
    b'\r\n'
    b'@app.route("/boms/<int:bom_id>/basic-prices.xlsx")\r\n'
    b'@login_required\r\n'
    b'def boms_basic_prices_xlsx(bom_id):\r\n'
    b'    bom, lines, grand_basic, cat_totals, cur, _ = _bom_basic_prices_compute(bom_id)\r\n'
    b'    import openpyxl\r\n'
    b'    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side\r\n'
    b'    from openpyxl.utils import get_column_letter\r\n'
    b'    wb = openpyxl.Workbook()\r\n'
    b'    ws = wb.active\r\n'
    b'    ws.title = "Basic Price Schedule"\r\n'
    b'    title_font  = Font(bold=True, size=14, color="0EA5E9")\r\n'
    b'    header_font = Font(bold=True, color="FFFFFF")\r\n'
    b'    header_fill = PatternFill("solid", fgColor="0E4A6A")\r\n'
    b'    cat_fill    = PatternFill("solid", fgColor="DBEAFE")\r\n'
    b'    bold = Font(bold=True)\r\n'
    b'    thin = Side(border_style="thin", color="D1D5DB")\r\n'
    b'    box  = Border(left=thin, right=thin, top=thin, bottom=thin)\r\n'
    b'    ws["A1"] = f"Basic Price Schedule -- {bom[\'title\']}"\r\n'
    b'    ws["A1"].font = title_font\r\n'
    b'    ws.merge_cells("A1:F1")\r\n'
    b'    ws["A2"] = f"Project: {bom[\'project_name\'] or \'-\'}"\r\n'
    b'    ws["A3"] = f"Client : {bom[\'client_name\'] or \'-\'}"\r\n'
    b'    ws["A4"] = f"Date   : {bom[\'updated_at\']}"\r\n'
    b'    ws["A5"] = "BASIC PRICE ONLY (no labour, OH, profit, contingency, VAT)."\r\n'
    b'    ws["A5"].font = bold\r\n'
    b'    headers = ["#", "Material", "Qty", "Unit", f"Basic price ({cur})", f"Subtotal ({cur})"]\r\n'
    b'    HROW = 7\r\n'
    b'    for col, h in enumerate(headers, 1):\r\n'
    b'        cell = ws.cell(row=HROW, column=col, value=h)\r\n'
    b'        cell.font = header_font\r\n'
    b'        cell.fill = header_fill\r\n'
    b'        cell.border = box\r\n'
    b'        cell.alignment = Alignment(horizontal="center")\r\n'
    b'    def _sanitize(v):\r\n'
    b'        s = str(v or "")\r\n'
    b'        return "\'" + s if s and s[0] in ("=", "+", "-", "@") else s\r\n'
    b'    row = HROW + 1\r\n'
    b'    prev_cat = None\r\n'
    b'    for idx, line in enumerate(lines, 1):\r\n'
    b'        it = line["item"]\r\n'
    b'        cat = line["category"]\r\n'
    b'        if cat != prev_cat:\r\n'
    b'            ws.cell(row=row, column=1, value=cat).font = bold\r\n'
    b'            ws.cell(row=row, column=1).fill = cat_fill\r\n'
    b'            ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=len(headers))\r\n'
    b'            row += 1\r\n'
    b'            prev_cat = cat\r\n'
    b'        ws.cell(row=row, column=1, value=idx)\r\n'
    b'        ws.cell(row=row, column=2, value=_sanitize(it["custom_name"]))\r\n'
    b'        ws.cell(row=row, column=3, value=float(line["qty"]))\r\n'
    b'        ws.cell(row=row, column=4, value=_sanitize(it["unit"]))\r\n'
    b'        ws.cell(row=row, column=5, value=round(float(line["basic_price"]), 2))\r\n'
    b'        ws.cell(row=row, column=6, value=round(float(line["subtotal"]), 2))\r\n'
    b'        for c in range(1, len(headers)+1):\r\n'
    b'            ws.cell(row=row, column=c).border = box\r\n'
    b'        row += 1\r\n'
    b'    # Grand total row\r\n'
    b'    ws.cell(row=row, column=5, value="Basic total").font = bold\r\n'
    b'    ws.cell(row=row, column=6, value=round(float(grand_basic), 2)).font = bold\r\n'
    b'    for c in (5, 6):\r\n'
    b'        ws.cell(row=row, column=c).border = box\r\n'
    b'    # Column widths\r\n'
    b'    widths = [5, 42, 8, 8, 18, 18]\r\n'
    b'    for i, w in enumerate(widths, 1):\r\n'
    b'        ws.column_dimensions[get_column_letter(i)].width = w\r\n'
    b'    try:\r\n'
    b'        _solarpro_xlsx_apply_borders_and_a4(ws)\r\n'
    b'    except Exception:\r\n'
    b'        pass\r\n'
    b'    import io as _io\r\n'
    b'    buf = _io.BytesIO()\r\n'
    b'    wb.save(buf)\r\n'
    b'    buf.seek(0)\r\n'
    b'    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", bom["title"])[:60]\r\n'
    b'    return send_file(buf,\r\n'
    b'                     mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",\r\n'
    b'                     as_attachment=True,\r\n'
    b'                     download_name=f"BasicPriceSchedule_{safe}.xlsx")\r\n'
    b'\r\n'
    b'\r\n'
    b'@app.route("/boms/<int:bom_id>/basic-prices.pdf")\r\n'
    b'@login_required\r\n'
    b'def boms_basic_prices_pdf(bom_id):\r\n'
    b'    bom, lines, grand_basic, cat_totals, cur, _ = _bom_basic_prices_compute(bom_id)\r\n'
    b'    md = []\r\n'
    b'    md.append(f"# Basic Price Schedule -- {bom[\'title\']}")\r\n'
    b'    if bom["project_name"]:\r\n'
    b'        md.append(f"**Project:** {bom[\'project_name\']}  ")\r\n'
    b'    if bom["client_name"]:\r\n'
    b'        md.append(f"**Client:** {bom[\'client_name\']}  ")\r\n'
    b'    md.append(f"**Generated:** {bom[\'updated_at\']}")\r\n'
    b'    md.append("")\r\n'
    b'    md.append("**Basic price only.** No labour, overhead, profit, contingency or VAT mark-ups.")\r\n'
    b'    md.append("")\r\n'
    b'    md.append("## Line items")\r\n'
    b'    md.append("")\r\n'
    b'    md.append(f"| # | Material | Qty | Unit | Basic price ({cur}) | Subtotal ({cur}) |")\r\n'
    b'    md.append("|---|---|---|---|---|---|")\r\n'
    b'    prev_cat = None\r\n'
    b'    for idx, line in enumerate(lines, 1):\r\n'
    b'        it = line["item"]\r\n'
    b'        if line["category"] != prev_cat:\r\n'
    b'            md.append(f"| | **{line[\'category\']}** |  |  |  |  |")\r\n'
    b'            prev_cat = line["category"]\r\n'
    b'        md.append(\r\n'
    b'            f"| {idx} | {it[\'custom_name\']} | {line[\'qty\']:.2f} | {it[\'unit\']} | "\r\n'
    b'            f"{line[\'basic_price\']:,.2f} | {line[\'subtotal\']:,.2f} |"\r\n'
    b'        )\r\n'
    b'    md.append("")\r\n'
    b'    md.append("## Category subtotals")\r\n'
    b'    md.append("")\r\n'
    b'    md.append(f"| Category | Subtotal ({cur}) |")\r\n'
    b'    md.append("|---|---|")\r\n'
    b'    for cat, sub in cat_totals.items():\r\n'
    b'        md.append(f"| {cat} | {sub:,.2f} |")\r\n'
    b'    md.append("")\r\n'
    b'    md.append(f"## Basic total\\n\\n**{cur} {grand_basic:,.2f}**\\n")\r\n'
    b'    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", bom["title"])[:60]\r\n'
    b'    return _render_pdf(\r\n'
    b'        f"Basic Price Schedule -- {bom[\'title\']}",\r\n'
    b'        "\\n".join(md),\r\n'
    b'        f"BasicPriceSchedule_{safe}.pdf",\r\n'
    b'    )\r\n'
    b'\r\n'
    b'\r\n'
    b'def _bom_basic_prices_pdf_bytes(bom_id):\r\n'
    b'    """Mirror of _bom_boq_pdf_bytes -- used by the email handler so the\r\n'
    b'    attached PDF == the downloaded PDF byte-for-byte."""\r\n'
    b'    uid = session.get("user_id") or 0\r\n'
    b'    if not uid:\r\n'
    b'        return b""\r\n'
    b'    with app.test_request_context("/_internal_basic_prices_pdf"):\r\n'
    b'        session["user_id"] = uid\r\n'
    b'        try:\r\n'
    b'            resp = boms_basic_prices_pdf(bom_id)\r\n'
    b'        except Exception as _e:\r\n'
    b'            try: app.logger.warning("basic-prices pdf bytes failed: %s", _e)\r\n'
    b'            except Exception: pass\r\n'
    b'            return b""\r\n'
    b'    try:\r\n'
    b'        return resp.get_data()\r\n'
    b'    except Exception:\r\n'
    b'        return b""\r\n'
    b'\r\n'
    b'\r\n'
    b'def _bom_basic_prices_xlsx_bytes(bom_id):\r\n'
    b'    return _xlsx_bytes_via_route(boms_basic_prices_xlsx, bom_id)\r\n'
    b'\r\n'
    b'\r\n'
    b'@app.route("/boms/<int:bom_id>/basic-prices/email", methods=["POST"])\r\n'
    b'@login_required\r\n'
    b'def boms_basic_prices_email(bom_id):\r\n'
    b'    """Email the Basic Price Schedule (no mark-ups) to a recipient.\r\n'
    b'    Attaches both PDF + Excel byte-identical to the downloads."""\r\n'
    b'    uid = session["user_id"]\r\n'
    b'    bom = _bom_owned_or_404(bom_id, uid)\r\n'
    b'    csrf_protect()\r\n'
    b'    to_email = (request.form.get("to_email") or "").strip().lower()[:200]\r\n'
    b'    if "@" not in to_email or "." not in to_email:\r\n'
    b'        flash("Invalid recipient email address.", "warning")\r\n'
    b'        return redirect(url_for("boms_basic_prices", bom_id=bom_id))\r\n'
    b'    subject = (request.form.get("subject")\r\n'
    b'               or f"Basic Price Schedule -- {bom[\'title\']}")[:200]\r\n'
    b'    body = (request.form.get("body")\r\n'
    b'            or f"Please find attached the basic price schedule \'{bom[\'title\']}\'.\\n"\r\n'
    b'               f"Basic prices only -- no mark-ups applied.\\n"\r\n'
    b'               f"Generated by SolarPro -- {bom[\'updated_at\']}.")\r\n'
    b'    safe_name = re.sub(r"[^A-Za-z0-9_.-]+", "_", bom["title"])[:60]\r\n'
    b'    pdf_bytes = b""\r\n'
    b'    try:\r\n'
    b'        pdf_bytes = _bom_basic_prices_pdf_bytes(bom_id)\r\n'
    b'    except Exception as _e:\r\n'
    b'        try: app.logger.warning("basic-prices email pdf failed: %s", _e)\r\n'
    b'        except Exception: pass\r\n'
    b'    xlsx_bytes = b""\r\n'
    b'    try:\r\n'
    b'        xlsx_bytes = _bom_basic_prices_xlsx_bytes(bom_id)\r\n'
    b'    except Exception as _e:\r\n'
    b'        try: app.logger.warning("basic-prices email xlsx failed: %s", _e)\r\n'
    b'        except Exception: pass\r\n'
    b'    if not pdf_bytes and not xlsx_bytes:\r\n'
    b'        flash("Could not build PDF or Excel attachment for email.", "danger")\r\n'
    b'        return redirect(url_for("boms_basic_prices", bom_id=bom_id))\r\n'
    b'    sent = False\r\n'
    b'    try:\r\n'
    b'        atts = []\r\n'
    b'        if pdf_bytes:\r\n'
    b'            atts.append((f"BasicPriceSchedule_{safe_name}.pdf", pdf_bytes, "application/pdf"))\r\n'
    b'        if xlsx_bytes:\r\n'
    b'            atts.append((f"BasicPriceSchedule_{safe_name}.xlsx", xlsx_bytes,\r\n'
    b'                         "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"))\r\n'
    b'        result = _send_email(to_email, subject, body, attachments=atts)\r\n'
    b'        sent = bool(result[0]) if isinstance(result, tuple) else bool(result)\r\n'
    b'    except Exception as _e:\r\n'
    b'        try: app.logger.warning("basic-prices email send failed: %s", _e)\r\n'
    b'        except Exception: pass\r\n'
    b'        sent = False\r\n'
    b'    flash(\r\n'
    b'        f"Email {\'sent\' if sent else \'failed -- check server log\'} to {to_email}.",\r\n'
    b'        "success" if sent else "warning",\r\n'
    b'    )\r\n'
    b'    return redirect(url_for("boms_basic_prices", bom_id=bom_id))\r\n'
    b'\r\n'
    b'\r\n'
)

pos = data.find(anchor_text)
line_start = data.rfind(b'\r\n', 0, pos) + 2
data = data[:line_start] + new_code + data[line_start:]

open(path, "wb").write(data)
print(f"OK: web_app.py {orig_len} -> {len(data)} bytes (+{len(data)-orig_len})")
