"""Task #12: Stage 1 BOM cost-free material-list exports.

Mirrors the Stage 2 pattern (basic-prices.xlsx/pdf/email) but emits
ONLY material columns (name, description, specification, qty, unit,
brand). NO price column anywhere. Honors the project rule that BOM
exports must not carry cost.
"""
import sys

path = "web_app.py"
data = open(path, "rb").read()
orig_len = len(data)

anchor_text = b'BOM item add / update / delete'
if data.count(anchor_text) != 1:
    print(f"FAIL: anchor 'BOM item add / update / delete' (got {data.count(anchor_text)})")
    sys.exit(1)

new_code = (
    b'# === Stage 1 BOM material-list exports (Task #12, 2026-06-24) ===\r\n'
    b'# Material list only -- NO price column, NO subtotal, NO grand total.\r\n'
    b'# For sending the BOM to a quantity surveyor / warehouse / installer\r\n'
    b'# without leaking any pricing. Cost stays on Stage 2 and Stage 3.\r\n'
    b'\r\n'
    b'def _bom_materials_rows(bom_id):\r\n'
    b'    """Shared helper: returns (bom, rows) where rows is a list of dicts\r\n'
    b'    with name, description, specification, category, qty, unit, brand.\r\n'
    b'    No price/rate/subtotal/total fields populated."""\r\n'
    b'    _ensure_bom_tables()\r\n'
    b'    uid = session["user_id"]\r\n'
    b'    bom = _bom_owned_or_404(bom_id, uid)\r\n'
    b'    items = _bom_items_with_prices(bom_id)\r\n'
    b'    rows = []\r\n'
    b'    for it in items:\r\n'
    b'        try:\r\n'
    b'            cat = (it["category_name"] if "category_name" in it.keys() else None) or "Uncategorised"\r\n'
    b'        except Exception:\r\n'
    b'            cat = "Uncategorised"\r\n'
    b'        try:\r\n'
    b'            desc = (it["description"] if "description" in it.keys() else None) or ""\r\n'
    b'        except Exception:\r\n'
    b'            desc = ""\r\n'
    b'        try:\r\n'
    b'            spec = ((it["specification"] if "specification" in it.keys() else None) or it["catalog_spec"] or "")\r\n'
    b'        except Exception:\r\n'
    b'            spec = ""\r\n'
    b'        try:\r\n'
    b'            brand = ((it["brand"] if "brand" in it.keys() and it["brand"] else None) or it["catalog_brand"] or "")\r\n'
    b'        except Exception:\r\n'
    b'            brand = ""\r\n'
    b'        rows.append({\r\n'
    b'            "name":          it["custom_name"],\r\n'
    b'            "description":   desc,\r\n'
    b'            "specification": spec,\r\n'
    b'            "category":      cat,\r\n'
    b'            "qty":           float(it["qty"] or 0),\r\n'
    b'            "unit":          it["unit"],\r\n'
    b'            "brand":         brand,\r\n'
    b'        })\r\n'
    b'    return bom, rows\r\n'
    b'\r\n'
    b'\r\n'
    b'@app.route("/boms/<int:bom_id>/materials.xlsx")\r\n'
    b'@login_required\r\n'
    b'def boms_materials_xlsx(bom_id):\r\n'
    b'    bom, rows = _bom_materials_rows(bom_id)\r\n'
    b'    import openpyxl\r\n'
    b'    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side\r\n'
    b'    from openpyxl.utils import get_column_letter\r\n'
    b'    wb = openpyxl.Workbook()\r\n'
    b'    ws = wb.active\r\n'
    b'    ws.title = "Materials"\r\n'
    b'    title_font  = Font(bold=True, size=14, color="F59E0B")\r\n'
    b'    header_font = Font(bold=True, color="FFFFFF")\r\n'
    b'    header_fill = PatternFill("solid", fgColor="4B5563")\r\n'
    b'    cat_fill    = PatternFill("solid", fgColor="FEF3C7")\r\n'
    b'    bold = Font(bold=True)\r\n'
    b'    thin = Side(border_style="thin", color="D1D5DB")\r\n'
    b'    box  = Border(left=thin, right=thin, top=thin, bottom=thin)\r\n'
    b'    ws["A1"] = f"Bill of Materials -- {bom[\'title\']}"\r\n'
    b'    ws["A1"].font = title_font\r\n'
    b'    ws.merge_cells("A1:G1")\r\n'
    b'    ws["A2"] = f"Project: {bom[\'project_name\'] or \'-\'}"\r\n'
    b'    ws["A3"] = f"Client : {bom[\'client_name\'] or \'-\'}"\r\n'
    b'    ws["A4"] = f"Date   : {bom[\'updated_at\']}"\r\n'
    b'    ws["A5"] = "MATERIAL LIST ONLY -- no pricing, no totals."\r\n'
    b'    ws["A5"].font = bold\r\n'
    b'    headers = ["#", "Material", "Description", "Specification", "Qty", "Unit", "Brand"]\r\n'
    b'    HROW = 7\r\n'
    b'    for col, h in enumerate(headers, 1):\r\n'
    b'        cell = ws.cell(row=HROW, column=col, value=h)\r\n'
    b'        cell.font = header_font\r\n'
    b'        cell.fill = header_fill\r\n'
    b'        cell.border = box\r\n'
    b'        cell.alignment = Alignment(horizontal="center")\r\n'
    b'    def _sanitize(v):\r\n'
    b'        s = str(v or "")\r\n'
    b'        return "\'" + s if s and s[0] in ("=", "+", "-", "@") else s\r\n'
    b'    r = HROW + 1\r\n'
    b'    prev_cat = None\r\n'
    b'    for idx, row in enumerate(rows, 1):\r\n'
    b'        if row["category"] != prev_cat:\r\n'
    b'            ws.cell(row=r, column=1, value=row["category"]).font = bold\r\n'
    b'            ws.cell(row=r, column=1).fill = cat_fill\r\n'
    b'            ws.merge_cells(start_row=r, start_column=1, end_row=r, end_column=len(headers))\r\n'
    b'            r += 1\r\n'
    b'            prev_cat = row["category"]\r\n'
    b'        ws.cell(row=r, column=1, value=idx)\r\n'
    b'        ws.cell(row=r, column=2, value=_sanitize(row["name"]))\r\n'
    b'        ws.cell(row=r, column=3, value=_sanitize(row["description"]))\r\n'
    b'        ws.cell(row=r, column=4, value=_sanitize(row["specification"]))\r\n'
    b'        ws.cell(row=r, column=5, value=row["qty"])\r\n'
    b'        ws.cell(row=r, column=6, value=_sanitize(row["unit"]))\r\n'
    b'        ws.cell(row=r, column=7, value=_sanitize(row["brand"]))\r\n'
    b'        for c in range(1, len(headers)+1):\r\n'
    b'            ws.cell(row=r, column=c).border = box\r\n'
    b'        r += 1\r\n'
    b'    widths = [5, 32, 36, 32, 8, 8, 18]\r\n'
    b'    for i, w in enumerate(widths, 1):\r\n'
    b'        ws.column_dimensions[get_column_letter(i)].width = w\r\n'
    b'    try:\r\n'
    b'        _solarpro_xlsx_apply_borders_and_a4(ws)\r\n'
    b'    except Exception:\r\n'
    b'        pass\r\n'
    b'    import io as _io\r\n'
    b'    buf = _io.BytesIO()\r\n'
    b'    wb.save(buf)\r\n'
    b'    buf.seek(0)\r\n'
    b'    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", bom["title"])[:60]\r\n'
    b'    return send_file(buf,\r\n'
    b'                     mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",\r\n'
    b'                     as_attachment=True,\r\n'
    b'                     download_name=f"BOM_{safe}.xlsx")\r\n'
    b'\r\n'
    b'\r\n'
    b'@app.route("/boms/<int:bom_id>/materials.pdf")\r\n'
    b'@login_required\r\n'
    b'def boms_materials_pdf(bom_id):\r\n'
    b'    bom, rows = _bom_materials_rows(bom_id)\r\n'
    b'    md = []\r\n'
    b'    md.append(f"# Bill of Materials -- {bom[\'title\']}")\r\n'
    b'    if bom["project_name"]:\r\n'
    b'        md.append(f"**Project:** {bom[\'project_name\']}  ")\r\n'
    b'    if bom["client_name"]:\r\n'
    b'        md.append(f"**Client:** {bom[\'client_name\']}  ")\r\n'
    b'    md.append(f"**Generated:** {bom[\'updated_at\']}")\r\n'
    b'    md.append("")\r\n'
    b'    md.append("**Material list only.** No pricing, no totals.")\r\n'
    b'    md.append("")\r\n'
    b'    md.append("## Items")\r\n'
    b'    md.append("")\r\n'
    b'    md.append("| # | Material | Description | Specification | Qty | Unit | Brand |")\r\n'
    b'    md.append("|---|---|---|---|---|---|---|")\r\n'
    b'    prev_cat = None\r\n'
    b'    for idx, row in enumerate(rows, 1):\r\n'
    b'        if row["category"] != prev_cat:\r\n'
    b'            md.append(f"| | **{row[\'category\']}** |  |  |  |  |  |")\r\n'
    b'            prev_cat = row["category"]\r\n'
    b'        md.append(\r\n'
    b'            f"| {idx} | {row[\'name\']} | {row[\'description\'] or \'-\'} | {row[\'specification\'] or \'-\'} | "\r\n'
    b'            f"{row[\'qty\']:.2f} | {row[\'unit\']} | {row[\'brand\'] or \'-\'} |"\r\n'
    b'        )\r\n'
    b'    md.append("")\r\n'
    b'    md.append(f"**Total line items:** {len(rows)}")\r\n'
    b'    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", bom["title"])[:60]\r\n'
    b'    return _render_pdf(\r\n'
    b'        f"Bill of Materials -- {bom[\'title\']}",\r\n'
    b'        "\\n".join(md),\r\n'
    b'        f"BOM_{safe}.pdf",\r\n'
    b'    )\r\n'
    b'\r\n'
    b'\r\n'
    b'def _bom_materials_pdf_bytes(bom_id):\r\n'
    b'    uid = session.get("user_id") or 0\r\n'
    b'    if not uid:\r\n'
    b'        return b""\r\n'
    b'    with app.test_request_context("/_internal_materials_pdf"):\r\n'
    b'        session["user_id"] = uid\r\n'
    b'        try:\r\n'
    b'            resp = boms_materials_pdf(bom_id)\r\n'
    b'        except Exception as _e:\r\n'
    b'            try: app.logger.warning("materials pdf bytes failed: %s", _e)\r\n'
    b'            except Exception: pass\r\n'
    b'            return b""\r\n'
    b'    try:\r\n'
    b'        return resp.get_data()\r\n'
    b'    except Exception:\r\n'
    b'        return b""\r\n'
    b'\r\n'
    b'\r\n'
    b'def _bom_materials_xlsx_bytes(bom_id):\r\n'
    b'    return _xlsx_bytes_via_route(boms_materials_xlsx, bom_id)\r\n'
    b'\r\n'
    b'\r\n'
    b'@app.route("/boms/<int:bom_id>/materials/email", methods=["POST"])\r\n'
    b'@login_required\r\n'
    b'def boms_materials_email(bom_id):\r\n'
    b'    """Email the cost-free Bill of Materials (no pricing) to a recipient.\r\n'
    b'    Attaches both PDF + Excel byte-identical to the downloads."""\r\n'
    b'    uid = session["user_id"]\r\n'
    b'    bom = _bom_owned_or_404(bom_id, uid)\r\n'
    b'    csrf_protect()\r\n'
    b'    to_email = (request.form.get("to_email") or "").strip().lower()[:200]\r\n'
    b'    if "@" not in to_email or "." not in to_email:\r\n'
    b'        flash("Invalid recipient email address.", "warning")\r\n'
    b'        return redirect(url_for("boms_view", bom_id=bom_id))\r\n'
    b'    subject = (request.form.get("subject")\r\n'
    b'               or f"Bill of Materials -- {bom[\'title\']}")[:200]\r\n'
    b'    body = (request.form.get("body")\r\n'
    b'            or f"Please find attached the bill of materials \'{bom[\'title\']}\'.\\n"\r\n'
    b'               f"Material list only -- no pricing.\\n"\r\n'
    b'               f"Generated by SolarPro -- {bom[\'updated_at\']}.")\r\n'
    b'    safe_name = re.sub(r"[^A-Za-z0-9_.-]+", "_", bom["title"])[:60]\r\n'
    b'    pdf_bytes = b""\r\n'
    b'    try:\r\n'
    b'        pdf_bytes = _bom_materials_pdf_bytes(bom_id)\r\n'
    b'    except Exception as _e:\r\n'
    b'        try: app.logger.warning("materials email pdf failed: %s", _e)\r\n'
    b'        except Exception: pass\r\n'
    b'    xlsx_bytes = b""\r\n'
    b'    try:\r\n'
    b'        xlsx_bytes = _bom_materials_xlsx_bytes(bom_id)\r\n'
    b'    except Exception as _e:\r\n'
    b'        try: app.logger.warning("materials email xlsx failed: %s", _e)\r\n'
    b'        except Exception: pass\r\n'
    b'    if not pdf_bytes and not xlsx_bytes:\r\n'
    b'        flash("Could not build PDF or Excel attachment for email.", "danger")\r\n'
    b'        return redirect(url_for("boms_view", bom_id=bom_id))\r\n'
    b'    sent = False\r\n'
    b'    try:\r\n'
    b'        atts = []\r\n'
    b'        if pdf_bytes:\r\n'
    b'            atts.append((f"BOM_{safe_name}.pdf", pdf_bytes, "application/pdf"))\r\n'
    b'        if xlsx_bytes:\r\n'
    b'            atts.append((f"BOM_{safe_name}.xlsx", xlsx_bytes,\r\n'
    b'                         "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"))\r\n'
    b'        result = _send_email(to_email, subject, body, attachments=atts)\r\n'
    b'        sent = bool(result[0]) if isinstance(result, tuple) else bool(result)\r\n'
    b'    except Exception as _e:\r\n'
    b'        try: app.logger.warning("materials email send failed: %s", _e)\r\n'
    b'        except Exception: pass\r\n'
    b'        sent = False\r\n'
    b'    flash(\r\n'
    b'        f"Email {\'sent\' if sent else \'failed -- check server log\'} to {to_email}.",\r\n'
    b'        "success" if sent else "warning",\r\n'
    b'    )\r\n'
    b'    return redirect(url_for("boms_view", bom_id=bom_id))\r\n'
    b'\r\n'
    b'\r\n'
)

pos = data.find(anchor_text)
line_start = data.rfind(b'\r\n', 0, pos) + 2
data = data[:line_start] + new_code + data[line_start:]

open(path, "wb").write(data)
print(f"OK: web_app.py {orig_len} -> {len(data)} bytes (+{len(data)-orig_len})")
