# patch_boq_xlsx_client_clean.py
# Phase 1 follow-up: rewrite the Excel BOQ export so it defaults to the
# client-clean 7-column layout and only reveals the rate build-up when
# ?include_buildup=1. Adds a Project Rate Build-Up sheet in that mode.

from pathlib import Path

TARGET = Path(__file__).with_name("web_app.py")
data = TARGET.read_bytes()

if b"# Phase 1 xlsx client-clean" in data:
    print("Already patched. No changes written.")
    raise SystemExit(0)

# Anchor: the entire current header-build + body-write + summary block.
OLD = (
    b'    # Title + meta\r\n'
    b'    ws["A1"] = f"Bill of Quantities \xe2\x80\x94 {bom[\'title\']}"\r\n'
    b'    ws["A1"].font = title_font\r\n'
    b'    ws.merge_cells("A1:I1")\r\n'
    b'    ws["A2"] = f"Project: {bom[\'project_name\'] or \'-\'}"\r\n'
    b'    ws["A3"] = f"Client : {bom[\'client_name\'] or \'-\'}"\r\n'
    b'    ws["A4"] = f"Date   : {bom[\'updated_at\']}"\r\n'
    b'    ws["A6"] = (\r\n'
    b'        f"Rates applied: labour {rates[\'labour_pct\']}% \xc2\xb7 overhead {rates[\'overhead_pct\']}% "\r\n'
    b'        f"\xc2\xb7 profit {rates[\'profit_pct\']}% \xc2\xb7 VAT {rates[\'vat_pct\']}%"\r\n'
    b'    )\r\n'
    b'    ws.merge_cells("A6:I6")\r\n'
    b'\r\n'
    b'    # Header row\r\n'
    b'    headers = ["#", "Description", "Category", "Qty", "Unit", "Basic (USD)",\r\n'
    b'               "Install (USD)", "Total Rate (USD)", "Amount (USD)"]\r\n'
    b'    HROW = 8\r\n'
    b'    for col, h in enumerate(headers, 1):\r\n'
    b'        cell = ws.cell(row=HROW, column=col, value=h)\r\n'
    b'        cell.font = header_font\r\n'
    b'        cell.fill = header_fill\r\n'
    b'        cell.border = box\r\n'
    b'        cell.alignment = Alignment(horizontal="center")\r\n'
    b'\r\n'
    b'    row = HROW + 1\r\n'
    b'    prev_cat = None\r\n'
    b'    for idx, line in enumerate(totals["lines"], 1):\r\n'
    b'        it = line["item"]\r\n'
    b'        cat = it["category_name"] or "Uncategorised"\r\n'
    b'        if cat != prev_cat:\r\n'
    b'            ws.cell(row=row, column=1, value=cat).font = bold\r\n'
    b'            ws.cell(row=row, column=1).fill = cat_fill\r\n'
    b'            ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=len(headers))\r\n'
    b'            row += 1\r\n'
    b'            prev_cat = cat\r\n'
    b'        # Excel cell-content safety: prefix any leading \'=\' with apostrophe\r\n'
    b'        # so Excel doesn\'t try to evaluate user-supplied text as a formula\r\n'
    b'        # (CSV/XLSX formula-injection defence).\r\n'
    b'        def _sanitize(v: str) -> str:\r\n'
    b'            s = str(v or "")\r\n'
    b'            return "\'" + s if s and s[0] in ("=", "+", "-", "@") else s\r\n'
    b'        ws.cell(row=row, column=1, value=idx)\r\n'
    b'        ws.cell(row=row, column=2, value=_sanitize(it["custom_name"]))\r\n'
    b'        ws.cell(row=row, column=3, value=_sanitize(cat))\r\n'
    b'        ws.cell(row=row, column=4, value=float(it["qty"] or 0))\r\n'
    b'        ws.cell(row=row, column=5, value=_sanitize(it["unit"]))\r\n'
    b'        ws.cell(row=row, column=6, value=round(line["basic_rate"], 2))\r\n'
    b'        ws.cell(row=row, column=7, value=round(line["install_labour"], 2))\r\n'
    b'        ws.cell(row=row, column=8, value=round(line["total_rate"], 2))\r\n'
    b'        ws.cell(row=row, column=9, value=round(line["line_total"], 2))\r\n'
    b'        for col in range(1, len(headers) + 1):\r\n'
    b'            ws.cell(row=row, column=col).border = box\r\n'
    b'        row += 1\r\n'
    b'\r\n'
    b'    # Subtotals + grand total\r\n'
    b'    row += 1\r\n'
    b'    for cat, sub in totals["category_totals"].items():\r\n'
    b'        ws.cell(row=row, column=2, value=f"{cat} subtotal").font = bold\r\n'
    b'        ws.cell(row=row, column=9, value=round(sub, 2)).font = bold\r\n'
    b'        row += 1\r\n'
    b'    row += 1\r\n'
    b'    ws.cell(row=row, column=2, value="GRAND TOTAL").font = title_font\r\n'
    b'    ws.cell(row=row, column=9, value=round(totals["grand_total"], 2)).font = title_font\r\n'
    b'\r\n'
    b'    # Column widths\r\n'
    b'    for col, w in enumerate([5, 40, 24, 8, 8, 14, 14, 14, 14], 1):\r\n'
    b'        ws.column_dimensions[get_column_letter(col)].width = w\r\n'
)

NEW = (
    b'    # Phase 1 xlsx client-clean: default columns per master prompt s11.\r\n'
    b'    # Add ?include_buildup=1 to also emit a "Project Rate Build-Up" sheet.\r\n'
    b'    include_buildup = bool(request.args.get("include_buildup") == "1")\r\n'
    b'    if include_buildup:\r\n'
    b'        try:\r\n'
    b'            from new_boq_hierarchy_schema import boq_audit\r\n'
    b'            boq_audit(get_db, uid, "boq_exported_internal", "marketplace_bom", bom_id, "xlsx")\r\n'
    b'        except Exception:\r\n'
    b'            pass\r\n'
    b'    cur_code = (bom["currency"] if "currency" in bom.keys() and bom["currency"] else "GHS")\r\n'
    b'\r\n'
    b'    # Title + meta\r\n'
    b'    ws["A1"] = f"Bill of Quantities \xe2\x80\x94 {bom[\'title\']}"\r\n'
    b'    ws["A1"].font = title_font\r\n'
    b'    ws.merge_cells("A1:G1")\r\n'
    b'    ws["A2"] = f"Project: {bom[\'project_name\'] or \'-\'}"\r\n'
    b'    ws["A3"] = f"Client : {bom[\'client_name\'] or \'-\'}"\r\n'
    b'    ws["A4"] = f"Date   : {bom[\'updated_at\']}"\r\n'
    b'\r\n'
    b'    # Client-clean BOQ sheet: # / Description / Unit / Qty / Rate / Amount / Remarks\r\n'
    b'    headers = ["#", "Description", "Unit", "Qty",\r\n'
    b'               f"Rate ({cur_code})", f"Amount ({cur_code})", "Remarks"]\r\n'
    b'    HROW = 6\r\n'
    b'    for col, h in enumerate(headers, 1):\r\n'
    b'        cell = ws.cell(row=HROW, column=col, value=h)\r\n'
    b'        cell.font = header_font\r\n'
    b'        cell.fill = header_fill\r\n'
    b'        cell.border = box\r\n'
    b'        cell.alignment = Alignment(horizontal="center")\r\n'
    b'\r\n'
    b'    # Excel cell-content safety: prefix any leading \'=\' with apostrophe\r\n'
    b'    # so Excel doesn\'t try to evaluate user-supplied text as a formula.\r\n'
    b'    def _sanitize(v):\r\n'
    b'        s = str(v or "")\r\n'
    b'        return "\'" + s if s and s[0] in ("=", "+", "-", "@") else s\r\n'
    b'\r\n'
    b'    row = HROW + 1\r\n'
    b'    prev_cat = None\r\n'
    b'    for idx, line in enumerate(totals["lines"], 1):\r\n'
    b'        it = line["item"]\r\n'
    b'        cat = it["category_name"] or "Uncategorised"\r\n'
    b'        if cat != prev_cat:\r\n'
    b'            ws.cell(row=row, column=1, value=cat).font = bold\r\n'
    b'            ws.cell(row=row, column=1).fill = cat_fill\r\n'
    b'            ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=len(headers))\r\n'
    b'            row += 1\r\n'
    b'            prev_cat = cat\r\n'
    b'        remarks = (it["remarks"] if "remarks" in it.keys() else None) or it["notes"] or ""\r\n'
    b'        ws.cell(row=row, column=1, value=idx)\r\n'
    b'        ws.cell(row=row, column=2, value=_sanitize(it["custom_name"]))\r\n'
    b'        ws.cell(row=row, column=3, value=_sanitize(it["unit"]))\r\n'
    b'        ws.cell(row=row, column=4, value=float(it["qty"] or 0))\r\n'
    b'        ws.cell(row=row, column=5, value=round(line["total_rate"], 2))\r\n'
    b'        ws.cell(row=row, column=6, value=round(line["line_total"], 2))\r\n'
    b'        ws.cell(row=row, column=7, value=_sanitize(remarks))\r\n'
    b'        for col in range(1, len(headers) + 1):\r\n'
    b'            ws.cell(row=row, column=col).border = box\r\n'
    b'        row += 1\r\n'
    b'\r\n'
    b'    # Subtotals + grand total\r\n'
    b'    row += 1\r\n'
    b'    for cat, sub in totals["category_totals"].items():\r\n'
    b'        ws.cell(row=row, column=2, value=f"{cat} subtotal").font = bold\r\n'
    b'        ws.cell(row=row, column=6, value=round(sub, 2)).font = bold\r\n'
    b'        row += 1\r\n'
    b'    row += 1\r\n'
    b'    ws.cell(row=row, column=2, value="GRAND TOTAL").font = title_font\r\n'
    b'    ws.cell(row=row, column=6, value=round(totals["grand_total"], 2)).font = title_font\r\n'
    b'\r\n'
    b'    for col, w in enumerate([5, 40, 8, 8, 14, 14, 30], 1):\r\n'
    b'        ws.column_dimensions[get_column_letter(col)].width = w\r\n'
    b'\r\n'
    b'    if include_buildup:\r\n'
    b'        # Project Rate Build-Up sheet (master prompt s12). Stored\r\n'
    b'        # separate from the BOQ; client-facing export omits it.\r\n'
    b'        ws3 = wb.create_sheet("Project Rate Build-Up")\r\n'
    b'        ws3["A1"] = f"Project Rate Build-Up \xe2\x80\x94 {bom[\'title\']}"\r\n'
    b'        ws3["A1"].font = title_font\r\n'
    b'        ws3.merge_cells("A1:L1")\r\n'
    b'        ws3["A2"] = "INTERNAL ONLY \xe2\x80\x94 do not share with client/tender."\r\n'
    b'        ws3["A2"].font = Font(bold=True, color="DC2626")\r\n'
    b'        ws3["A4"] = (\r\n'
    b'            f"Rates: labour {rates[\'labour_pct\']}% \xc2\xb7 overhead {rates[\'overhead_pct\']}% "\r\n'
    b'            f"\xc2\xb7 profit {rates[\'profit_pct\']}% \xc2\xb7 VAT {rates[\'vat_pct\']}%"\r\n'
    b'        )\r\n'
    b'        bu_headers = ["#", "Description", "Category", "Qty", "Unit",\r\n'
    b'                      f"Basic ({cur_code})", f"Supply ({cur_code})", f"Install ({cur_code})",\r\n'
    b'                      f"+OH ({cur_code})", f"+Profit ({cur_code})", f"+VAT ({cur_code})",\r\n'
    b'                      f"Final Rate ({cur_code})", f"Amount ({cur_code})"]\r\n'
    b'        HROW3 = 6\r\n'
    b'        for col, h in enumerate(bu_headers, 1):\r\n'
    b'            cell = ws3.cell(row=HROW3, column=col, value=h)\r\n'
    b'            cell.font = header_font\r\n'
    b'            cell.fill = header_fill\r\n'
    b'            cell.border = box\r\n'
    b'            cell.alignment = Alignment(horizontal="center")\r\n'
    b'        r3 = HROW3 + 1\r\n'
    b'        for idx, line in enumerate(totals["lines"], 1):\r\n'
    b'            it = line["item"]\r\n'
    b'            cat = it["category_name"] or "Uncategorised"\r\n'
    b'            ws3.cell(row=r3, column=1, value=idx)\r\n'
    b'            ws3.cell(row=r3, column=2, value=_sanitize(it["custom_name"]))\r\n'
    b'            ws3.cell(row=r3, column=3, value=_sanitize(cat))\r\n'
    b'            ws3.cell(row=r3, column=4, value=float(it["qty"] or 0))\r\n'
    b'            ws3.cell(row=r3, column=5, value=_sanitize(it["unit"]))\r\n'
    b'            ws3.cell(row=r3, column=6, value=round(line["basic_rate"], 2))\r\n'
    b'            ws3.cell(row=r3, column=7, value=round(line["basic_rate"], 2))\r\n'
    b'            ws3.cell(row=r3, column=8, value=round(line["install_labour"], 2))\r\n'
    b'            ws3.cell(row=r3, column=9, value=round(line["overhead"], 2))\r\n'
    b'            ws3.cell(row=r3, column=10, value=round(line["profit"], 2))\r\n'
    b'            ws3.cell(row=r3, column=11, value=round(line["vat"], 2))\r\n'
    b'            ws3.cell(row=r3, column=12, value=round(line["total_rate"], 2))\r\n'
    b'            ws3.cell(row=r3, column=13, value=round(line["line_total"], 2))\r\n'
    b'            r3 += 1\r\n'
    b'        for col, w in enumerate([5, 36, 18, 7, 7, 12, 12, 12, 10, 10, 10, 14, 14], 1):\r\n'
    b'            ws3.column_dimensions[get_column_letter(col)].width = w\r\n'
)

assert data.count(OLD) == 1, f"xlsx anchor count={data.count(OLD)}"
data = data.replace(OLD, NEW)
TARGET.write_bytes(data)
print(f"OK -- patched xlsx route (+{len(NEW)-len(OLD)} bytes)")
