# --- Patch -- marketplace catalogue taxonomy + sample seed expansion -----------
# Drives "Use the prompt to do update in the supplier and equipment catalogues"
# from `pvsolar1/price master/price prompt.txt`.
#
# What this patch does, byte-level, on web_app.py:
#   1. Adds a 21st category -- Power System Equipment (RMU, Generators, UPS, etc.)
#      requested in the prompt's "Power System Equipment" section.
#   2. Adds three central registries the supplier upload form + Specification
#      Validation Agent + BOQ generator will draw from:
#         _MARKETPLACE_SUBCATEGORIES  -- code -> list of subcategory display names
#         _MARKETPLACE_DEFAULT_UNIT   -- code -> default unit of measure
#         _MARKETPLACE_SPEC_FIELDS    -- code -> list of required spec fields
#      All three derived from the taxonomy in price prompt.txt sec 7 + sec 1-sec 18.
#   3. Extends _seed_marketplace_samples (SQLite) with ~40 more starter rows
#      so every category from the prompt has live magnet content on first visit.
#   4. Same expansion for _seed_marketplace_postgres_samples (ASCII-only spec
#      strings -- Postgres seed deliberately avoids mm² / ± to stay encoding-clean).
#   5. Adds Eaton + Hager + Legrand + Siemens + RR Kabel + Polycab to the
#      Postgres extra-suppliers list so the new samples have credible vendors.
#
# Idempotent -- refuses to apply if the new category line already exists, so
# re-running on an already-patched file is a no-op.

import sys
from pathlib import Path

TARGET = Path(__file__).with_name("web_app.py")
data = TARGET.read_bytes()

SENTINEL_NEW_CAT = b'("power_system",      "Power System Equipment"'
if SENTINEL_NEW_CAT in data:
    print("Already patched. No changes written.")
    sys.exit(0)

# -- Patch A: extend _MARKETPLACE_CATEGORIES + inject 3 taxonomy dicts --------
CAT_OLD = (
    b'    ("ict_elv",           "ICT / ELV Products",               "bi-router",           200),\r\n'
    b']\r\n'
)
CAT_NEW = (
    b'    ("ict_elv",           "ICT / ELV Products",               "bi-router",           200),\r\n'
    b'    ("power_system",      "Power System Equipment",           "bi-cpu",              210),\r\n'
    b']\r\n'
    b'\r\n'
    b'# Subcategory taxonomy -- source of truth for the supplier product upload form\'s\r\n'
    b'# subcategory dropdown and the BOQ generator\'s section mapping. Keep aligned\r\n'
    b'# with pvsolar1/price master/price prompt.txt sections 1-18 + Power System.\r\n'
    b'_MARKETPLACE_SUBCATEGORIES = {\r\n'
    b'    "transformers": [\r\n'
    b'        "Oil Immersed", "Dry Type", "Distribution", "Step-up", "Step-down",\r\n'
    b'        "Package Substation",\r\n'
    b'    ],\r\n'
    b'    "avr": [\r\n'
    b'        "Single-phase", "Three-phase", "Servo", "Static", "Industrial",\r\n'
    b'    ],\r\n'
    b'    "hv_cables": [\r\n'
    b'        "1C HV Armoured", "3C HV Armoured", "XLPE Insulated",\r\n'
    b'        "Copper HV", "Aluminium HV",\r\n'
    b'    ],\r\n'
    b'    "lv_cables": [\r\n'
    b'        "1C Armoured", "2C Armoured", "3C Armoured", "4C Armoured", "5C Armoured",\r\n'
    b'        "XLPE/SWA/PVC", "PVC/SWA/PVC", "Flexible Power",\r\n'
    b'    ],\r\n'
    b'    "wires": [\r\n'
    b'        "Single Core PVC", "Flexible", "Fire-resistant", "Earth Wire",\r\n'
    b'        "Control Wire", "Lighting Circuit", "Socket Circuit",\r\n'
    b'    ],\r\n'
    b'    "panel_boards": [\r\n'
    b'        "Main Panel", "Sub-main Panel", "Meter Panel", "ATS Panel",\r\n'
    b'        "Synchronising", "MCC Panel", "PFC Panel", "Custom Control",\r\n'
    b'    ],\r\n'
    b'    "distribution_boards": [\r\n'
    b'        "SPN", "TPN", "Surface Mounted", "Flush Mounted", "Metal Clad",\r\n'
    b'        "Consumer Unit", "Final Circuit",\r\n'
    b'    ],\r\n'
    b'    "isolators": [\r\n'
    b'        "Single-pole", "Double-pole", "Three-pole", "Four-pole",\r\n'
    b'        "AC", "DC", "Weatherproof",\r\n'
    b'    ],\r\n'
    b'    "fuse_switches": [\r\n'
    b'        "Switch Fuse Unit", "Fuse Switch Disconnector", "HRC",\r\n'
    b'        "LV Fuse Switch", "Changeover",\r\n'
    b'    ],\r\n'
    b'    "conduit": [\r\n'
    b'        "PVC", "Heavy Gauge PVC", "Flexible", "GI", "Steel", "Corrugated",\r\n'
    b'    ],\r\n'
    b'    "steel_boxes": [\r\n'
    b'        "1 Gang", "2 Gang", "3 Gang", "4 Gang",\r\n'
    b'        "Deep", "Surface", "Flush",\r\n'
    b'    ],\r\n'
    b'    "circular_boxes": [\r\n'
    b'        "PVC Circular", "Steel Circular", "Ceiling", "Junction",\r\n'
    b'    ],\r\n'
    b'    "cable_trays": [\r\n'
    b'        "Perforated", "Ladder", "Wire Mesh", "Heavy Duty",\r\n'
    b'        "Galvanised", "Stainless Steel",\r\n'
    b'    ],\r\n'
    b'    "trunking": [\r\n'
    b'        "Mini", "PVC", "Cable Management", "Dado", "Skirting", "Compartment",\r\n'
    b'    ],\r\n'
    b'    "earthing": [\r\n'
    b'        "Earth Rods", "Earth Bars", "Earth Clamps", "Copper Tape",\r\n'
    b'        "Inspection Pits", "Earth Cables", "Chemical Earthing",\r\n'
    b'        "Exothermic Kits",\r\n'
    b'    ],\r\n'
    b'    "sockets": [\r\n'
    b'        "Switched", "Unswitched", "USB", "Weatherproof",\r\n'
    b'        "Metal Clad", "Flush", "Surface",\r\n'
    b'    ],\r\n'
    b'    "dp_switches": [\r\n'
    b'        "Water Heater", "Air Conditioner", "Appliance",\r\n'
    b'        "Neon Indicator", "Metal Clad",\r\n'
    b'    ],\r\n'
    b'    "light_switches": [\r\n'
    b'        "1 Gang 1 Way", "1 Gang 2 Way", "2 Gang 1 Way", "2 Gang 2 Way",\r\n'
    b'        "3 Gang 1 Way", "3 Gang 2 Way", "4 Gang",\r\n'
    b'        "Intermediate", "Dimmer", "Key Switch",\r\n'
    b'    ],\r\n'
    b'    "solar_equipment": [\r\n'
    b'        "PV Modules", "Hybrid Inverters", "String Inverters", "Micro Inverters",\r\n'
    b'        "Batteries", "Charge Controllers", "DC Isolators", "DC SPD",\r\n'
    b'        "MC4 Connectors", "Solar Cables", "Mounting Systems",\r\n'
    b'        "Combiner Boxes", "Monitoring Systems",\r\n'
    b'    ],\r\n'
    b'    "power_system": [\r\n'
    b'        "RMU", "Generators", "UPS", "Static Transfer Switches",\r\n'
    b'        "Capacitor Banks", "Busduct Systems", "Switchgear",\r\n'
    b'        "Protection Relays",\r\n'
    b'    ],\r\n'
    b'    "ict_elv": [\r\n'
    b'        "Data Outlets", "Network Switches", "Access Points", "CCTV",\r\n'
    b'        "Fire Alarm", "Access Control", "Nurse Call",\r\n'
    b'        "Structured Cabling", "Telephones",\r\n'
    b'    ],\r\n'
    b'}\r\n'
    b'\r\n'
    b'# Default unit of measure per category -- picked from the prompt\'s\r\n'
    b'# "Default units" block. Used to pre-fill the supplier upload form.\r\n'
    b'_MARKETPLACE_DEFAULT_UNIT = {\r\n'
    b'    "transformers":        "No.",\r\n'
    b'    "avr":                 "No.",\r\n'
    b'    "hv_cables":           "m",\r\n'
    b'    "lv_cables":           "m",\r\n'
    b'    "wires":               "Roll",\r\n'
    b'    "panel_boards":        "No.",\r\n'
    b'    "distribution_boards": "No.",\r\n'
    b'    "isolators":           "No.",\r\n'
    b'    "fuse_switches":       "No.",\r\n'
    b'    "conduit":             "m",\r\n'
    b'    "steel_boxes":         "No.",\r\n'
    b'    "circular_boxes":      "No.",\r\n'
    b'    "cable_trays":         "m",\r\n'
    b'    "trunking":            "m",\r\n'
    b'    "earthing":            "No.",\r\n'
    b'    "sockets":             "No.",\r\n'
    b'    "dp_switches":         "No.",\r\n'
    b'    "light_switches":      "No.",\r\n'
    b'    "solar_equipment":     "No.",\r\n'
    b'    "power_system":        "No.",\r\n'
    b'    "ict_elv":             "No.",\r\n'
    b'}\r\n'
    b'\r\n'
    b'# Required spec fields per category -- surfaces in the supplier upload form\r\n'
    b'# so suppliers know what the Specification Validation Agent will check for.\r\n'
    b'# Drawn straight from price prompt.txt sections 1-18.\r\n'
    b'_MARKETPLACE_SPEC_FIELDS = {\r\n'
    b'    "transformers": [\r\n'
    b'        "kVA rating", "Voltage ratio", "Phase", "Frequency",\r\n'
    b'        "Cooling type", "Impedance", "Vector group",\r\n'
    b'        "Protection class", "Enclosure type",\r\n'
    b'    ],\r\n'
    b'    "avr": [\r\n'
    b'        "kVA rating", "Input voltage range", "Output voltage",\r\n'
    b'        "Phase", "Regulation accuracy", "Response time", "Bypass arrangement",\r\n'
    b'    ],\r\n'
    b'    "hv_cables": [\r\n'
    b'        "Voltage rating", "Conductor material", "Number of cores",\r\n'
    b'        "Conductor size", "Insulation type", "Armour type", "Sheath type",\r\n'
    b'        "Fire rating",\r\n'
    b'    ],\r\n'
    b'    "lv_cables": [\r\n'
    b'        "Conductor material", "Number of cores", "Cable size",\r\n'
    b'        "Insulation", "Armour", "Sheath", "Voltage rating",\r\n'
    b'    ],\r\n'
    b'    "wires": [\r\n'
    b'        "Conductor material", "Wire size", "Insulation type",\r\n'
    b'        "Colour", "Voltage rating", "Roll length",\r\n'
    b'    ],\r\n'
    b'    "panel_boards": [\r\n'
    b'        "Current rating", "Short circuit rating", "Number of ways",\r\n'
    b'        "Enclosure type", "IP rating", "Busbar rating",\r\n'
    b'        "Incomer type", "Outgoing protection", "Form of separation",\r\n'
    b'    ],\r\n'
    b'    "distribution_boards": [\r\n'
    b'        "Number of ways", "Phase", "Incomer rating", "Busbar rating",\r\n'
    b'        "Enclosure material", "Mounting type", "Protection type",\r\n'
    b'    ],\r\n'
    b'    "isolators": [\r\n'
    b'        "Current rating", "Voltage rating", "Number of poles",\r\n'
    b'        "IP rating", "Mounting type", "Application",\r\n'
    b'    ],\r\n'
    b'    "fuse_switches": [\r\n'
    b'        "Current rating", "Voltage rating", "Number of poles",\r\n'
    b'        "Fuse type", "Breaking capacity", "Enclosure type", "Mounting type",\r\n'
    b'    ],\r\n'
    b'    "conduit": [\r\n'
    b'        "Diameter", "Material", "Length", "Gauge", "Colour",\r\n'
    b'    ],\r\n'
    b'    "steel_boxes": [\r\n'
    b'        "Size", "Gang", "Depth", "Material", "Finish", "Mounting type",\r\n'
    b'    ],\r\n'
    b'    "circular_boxes": [\r\n'
    b'        "Diameter", "Depth", "Material", "Number of knockouts", "Mounting type",\r\n'
    b'    ],\r\n'
    b'    "cable_trays": [\r\n'
    b'        "Width", "Depth", "Thickness", "Material", "Finish", "Length",\r\n'
    b'    ],\r\n'
    b'    "trunking": [\r\n'
    b'        "Width", "Height", "Length", "Material", "Colour", "Compartments",\r\n'
    b'    ],\r\n'
    b'    "earthing": [\r\n'
    b'        "Material", "Size", "Length", "Cross-sectional area",\r\n'
    b'        "Coating", "Application",\r\n'
    b'    ],\r\n'
    b'    "sockets": [\r\n'
    b'        "Current rating", "Voltage rating", "Number of gangs",\r\n'
    b'        "Switched/unswitched", "Finish", "Mounting type", "IP rating",\r\n'
    b'    ],\r\n'
    b'    "dp_switches": [\r\n'
    b'        "Current rating", "Voltage rating", "Pole type",\r\n'
    b'        "Neon indicator", "Mounting type", "Finish",\r\n'
    b'    ],\r\n'
    b'    "light_switches": [\r\n'
    b'        "Gang", "Way", "Current rating", "Voltage rating",\r\n'
    b'        "Finish", "Mounting type",\r\n'
    b'    ],\r\n'
    b'    "solar_equipment": [\r\n'
    b'        "Rated power / capacity", "Voltage", "Efficiency",\r\n'
    b'        "Warranty period", "Certifications", "IP rating",\r\n'
    b'    ],\r\n'
    b'    "power_system": [\r\n'
    b'        "Rated power", "Voltage", "Current rating", "Phase",\r\n'
    b'        "Frequency", "Protection class", "Cooling / fuel type",\r\n'
    b'    ],\r\n'
    b'    "ict_elv": [\r\n'
    b'        "Standard / category", "Ports / channels", "Power source",\r\n'
    b'        "Mounting type", "Compliance",\r\n'
    b'    ],\r\n'
    b'}\r\n'
)

assert data.count(CAT_OLD) == 1, f"Patch A anchor not unique (count={data.count(CAT_OLD)})"
data = data.replace(CAT_OLD, CAT_NEW)

# -- Patch B: extend SQLite seed (mojibake-style unicode preserved) -----------
SQLITE_OLD = (
    b'        ("light_switches",     "3 Gang 2 Way Switch",                  "MK",        "K4873WHI",   "3 gang 2 way switch, 10A, white",                    "No.",    11, rs,        7,  "3 Gang 2 Way"),\r\n'
    b'    ]\r\n'
    b'    # Build a code \xe2\x86\x92 display-name map from the seed list so the legacy\r\n'
)
SQLITE_NEW = (
    b'        ("light_switches",     "3 Gang 2 Way Switch",                  "MK",        "K4873WHI",   "3 gang 2 way switch, 10A, white",                    "No.",    11, rs,        7,  "3 Gang 2 Way"),\r\n'
    b'        # - Extra coverage so every category has \xe2\x89\xa53 starter rows --------------\r\n'
    b'        ("transformers",       "Schneider 100 kVA Dry Type",           "Schneider", "DT100",      "100 kVA, 11/0.4 kV, AN, IP00, IEC 60076-11",         "No.",  4200, schneider, 60, "Dry Type"),\r\n'
    b'        ("transformers",       "ABB 1000 kVA Package Substation",      "ABB",       "PSS-1000",   "1000 kVA, 11/0.4 kV, ONAN, Dyn11, packaged unit",    "No.", 18500, schneider, 75, "Package Substation"),\r\n'
    b'        ("avr",                "Static AVR 10 kVA 1-Phase",            "Generic",   "SAVR-10K-1P", "10 kVA, 1PH, Static IGBT, \xc2\xb13% accuracy",             "No.",   620, rs,        14, "Single-phase"),\r\n'
    b'        ("hv_cables",          "33 kV XLPE 1C 240mm\xc2\xb2 Cu Armoured",     "Nexans",    "HV-33-1C240","33 kV, XLPE/CWS/PVC, Copper, 1 core, 240mm\xc2\xb2",       "m",     145, rs,        45, "1C HV Armoured"),\r\n'
    b'        ("hv_cables",          "11 kV 3C 95mm\xc2\xb2 Al Armoured",            "Nexans",    "HV-11-3C95A","11 kV, XLPE/SWA/PVC, Aluminium, 3 core, 95mm\xc2\xb2",     "m",      38, rs,        45, "Aluminium HV"),\r\n'
    b'        ("lv_cables",          "LV 2C 4mm\xc2\xb2 Cu PVC/SWA/PVC",            "Nexans",    "LV-2C-4P",   "0.6/1 kV, 2 core, 4mm\xc2\xb2, Cu, PVC/SWA/PVC",          "m",       6, rs,        14, "PVC/SWA/PVC"),\r\n'
    b'        ("lv_cables",          "LV 3C 6mm\xc2\xb2 Cu Flex H07RN-F",           "Nexans",    "FLX-3C-6",   "450/750 V, 3 core, 6mm\xc2\xb2, Cu, rubber-sheathed",     "m",       8, rs,        14, "Flexible Power"),\r\n'
    b'        ("wires",              "Earth Wire 6mm\xc2\xb2 Green/Yellow (100m)",  "Polycab",   "EW-6-GY",    "6mm\xc2\xb2 Cu, 450/750 V, PVC, green/yellow",            "Roll",   48, rs,        7,  "Earth Wire"),\r\n'
    b'        ("wires",              "Fire-resistant 1.5mm\xc2\xb2 (100m)",         "RR Kabel",  "FR-1.5",     "1.5mm\xc2\xb2 Cu, FR-LSZH, 450/750 V, red",               "Roll",   58, rs,        14, "Fire-resistant"),\r\n'
    b'        ("panel_boards",       "1000A ATS Panel",                      "Schneider", "ATS-1000",   "1000A 3PH ATS, AMF + utility/genset, IP54",          "No.", 14500, schneider, 60, "ATS Panel"),\r\n'
    b'        ("panel_boards",       "200kVAr PFC Panel",                    "Schneider", "PFC-200",    "200 kVAr, 10 stages, contactor-switched, IP42",      "No.",  6200, schneider, 45, "PFC Panel"),\r\n'
    b'        ("distribution_boards","12-way Metal Clad TPN DB",             "Hager",     "DB-12MCTPN", "12-way TPN MC, 125A incomer, 10kA, IP54",            "No.",   320, schneider, 21, "Metal Clad"),\r\n'
    b'        ("distribution_boards","6-way Flush Consumer Unit",            "Hager",     "DB-6FCU",    "6-way SPN flush, 63A RCD + 6 MCBs",                  "No.",   135, schneider, 14, "Flush Mounted"),\r\n'
    b'        ("isolators",          "32A 2-Pole AC Isolator IP65",          "Schneider", "ISO-32-2P",  "32A 2P AC isolator, IP65, weatherproof",             "No.",    24, schneider, 14, "Double-pole"),\r\n'
    b'        ("isolators",          "16A 4-Pole DC Isolator (Solar)",       "Schneider", "ISO-16-DC",  "16A 4P DC isolator, 1000 VDC, IP65, lockable",       "No.",    42, schneider, 21, "DC"),\r\n'
    b'        ("fuse_switches",      "200A Fuse Switch Disconnector",        "ABB",       "FSD-200",    "200A 4P FSD, 50kA, HRC fuses, IP30",                 "No.",   245, schneider, 21, "Fuse Switch Disconnector"),\r\n'
    b'        ("fuse_switches",      "400A Changeover Fuse Switch",          "ABB",       "CFS-400",    "400A 4P changeover, manual, IP31",                   "No.",   485, schneider, 30, "Changeover"),\r\n'
    b'        ("conduit",            "GI Conduit 20mm (3m)",                 "Generic",   "GI-20",      "20mm dia hot-dip galv steel conduit, 3m, class 4",   "m",       2, rs,        7,  "GI"),\r\n'
    b'        ("conduit",            "Flexible Metallic 25mm (per m)",       "Generic",   "FLX-25M",    "25mm dia flexible metallic conduit, PVC-coated",     "m",       3, rs,        7,  "Flexible"),\r\n'
    b'        ("steel_boxes",        "3 Gang Surface Steel Box",             "Generic",   "SB-3G-S",    "3 gang surface flush steel back box, 35mm deep",     "No.",     5, rs,        7,  "3 Gang"),\r\n'
    b'        ("steel_boxes",        "4 Gang Deep Steel Box",                "Generic",   "SB-4G-D",    "4 gang deep flush steel back box, 50mm deep",        "No.",     6, rs,        7,  "4 Gang"),\r\n'
    b'        ("circular_boxes",     "PVC Junction Box 80mm IP65",           "Generic",   "JB-PVC-80",  "80mm PVC junction box, 4 knockouts, IP65",           "No.",     3, rs,        7,  "Junction"),\r\n'
    b'        ("cable_trays",        "Ladder Tray 450mm (3m) HDG",           "Generic",   "LT-450",     "450mm wide ladder cable tray, HDG, 3m length",       "m",      32, rs,        21, "Ladder"),\r\n'
    b'        ("cable_trays",        "Wire Mesh Tray 200mm (3m)",            "Generic",   "WMT-200",    "200mm wide wire-mesh basket tray, EZ, 3m",           "m",      14, rs,        14, "Wire Mesh"),\r\n'
    b'        ("trunking",           "Dado Trunking 100x50mm (2m)",          "Generic",   "DT-100-50",  "100x50mm dado trunking, 2 compartments, white",      "m",      18, rs,        14, "Dado"),\r\n'
    b'        ("trunking",           "Skirting Trunking 75x18mm (2m)",       "Generic",   "ST-75-18",   "75x18mm skirting trunking, white",                   "m",       8, rs,        7,  "Skirting"),\r\n'
    b'        ("earthing",           "Earth Rod 16mm x 1.2m Cu-bonded",      "Generic",   "ER-16-1.2",  "16mm x 1.2m Cu-bonded steel earth rod with clamp",   "No.",    18, rs,        7,  "Earth Rods"),\r\n'
    b'        ("earthing",           "Copper Tape 25x3mm (10m roll)",        "Generic",   "CT-25-3",    "25x3mm bare Cu tape, 10m roll, lightning protection","Roll",   95, rs,        14, "Copper Tape"),\r\n'
    b'        ("earthing",           "Exothermic Weld Kit (Cu/Cu Tee)",      "Generic",   "EXO-CC-T",   "Exothermic weld kit, Cu/Cu tee, 95mm\xc2\xb2",              "No.",    32, rs,        14, "Exothermic Kits"),\r\n'
    b'        ("sockets",            "13A IP66 Weatherproof Twin Socket",    "MK",        "K56480WHI",  "13A twin switched, IP66, surface, grey",             "No.",    28, mk,        14, "Weatherproof"),\r\n'
    b'        ("sockets",            "13A Metal Clad Twin Socket",           "MK",        "K2747ALM",   "13A twin switched, metal-clad, surface",             "No.",    22, mk,        14, "Metal Clad"),\r\n'
    b'        ("dp_switches",        "20A DP AC Switch with Neon",           "MK",        "K5423WHI",   "20A DP switch with neon, flush, for AC, white",      "No.",    13, mk,        7,  "Air Conditioner"),\r\n'
    b'        ("dp_switches",        "20A Metal Clad DP Switch",             "MK",        "K5403ALM",   "20A DP switch, metal-clad surface, IP2X",            "No.",    16, mk,        14, "Metal Clad"),\r\n'
    b'        ("light_switches",     "1 Gang 1 Way Switch",                  "MK",        "K4870WHI",   "1 gang 1 way switch, 10A, white",                    "No.",     5, mk,        7,  "1 Gang 1 Way"),\r\n'
    b'        ("light_switches",     "4 Gang 2 Way Switch",                  "MK",        "K4874WHI",   "4 gang 2 way switch, 10A, white",                    "No.",    14, mk,        7,  "4 Gang"),\r\n'
    b'        ("light_switches",     "Intermediate Switch 1G",               "MK",        "K4875WHI",   "1 gang intermediate switch, 10A, white",             "No.",     9, mk,        7,  "Intermediate"),\r\n'
    b'        ("light_switches",     "Dimmer Switch 1G 400W",                "MK",        "K1500WHI",   "1 gang push-rotary dimmer, 60-400W, white",          "No.",    18, mk,        7,  "Dimmer"),\r\n'
    b'        ("solar_equipment",    "JA Solar 550W Mono PV Module",         "JA Solar",  "JAM72S30-550","550W, mono-PERC, 72-cell, 21.3% eff., 12-yr product","No.",   180, rs,        21, "PV Modules"),\r\n'
    b'        ("solar_equipment",    "Victron MultiPlus-II 5kVA Inverter",   "Victron",   "PMP482505010","5 kVA hybrid, 48V, 70A charger, parallel-stackable",  "No.",  1480, rs,        14, "Hybrid Inverters"),\r\n'
    b'        ("solar_equipment",    "Pylontech US5000 4.8kWh LFP Battery",  "Pylontech", "US5000",     "4.8 kWh, 48V, LFP, 6000 cycles @ 80% DoD",           "No.",  1380, rs,        21, "Batteries"),\r\n'
    b'        ("solar_equipment",    "MC4 Connector Pair (TUV)",             "Generic",   "MC4-PAIR",   "MC4 male+female connector pair, TUV, 1500 VDC",      "No.",     2, rs,        7,  "MC4 Connectors"),\r\n'
    b'        ("solar_equipment",    "DC Combiner Box 4-in/1-out 1000V",     "Generic",   "DCB-4-1",    "4-in/1-out DC combiner, 1000 VDC, SPD + fuses, IP65","No.",   145, rs,        14, "Combiner Boxes"),\r\n'
    b'        ("power_system",       "11 kV RMU 2-Way Compact",              "ABB",       "SafeRing-2W","11 kV, 2-way ring main unit, SF6, 630A, 21kA",       "No.", 11500, schneider, 75, "RMU"),\r\n'
    b'        ("power_system",       "250 kVA Cummins Genset",               "Cummins",   "C250D5",     "250 kVA, 3PH, diesel, open-set, 1500 rpm",           "No.", 28500, rs,        45, "Generators"),\r\n'
    b'        ("power_system",       "10 kVA Online UPS Tower",              "APC",       "SRT10KXLI",  "10 kVA / 10 kW, online double-conversion, tower",    "No.",  4600, rs,        21, "UPS"),\r\n'
    b'        ("power_system",       "MCCB 400A 4P 50kA",                    "Schneider", "MCCB-400-4P","400A 4P MCCB, 50kA breaking capacity",               "No.",   520, schneider, 21, "Switchgear"),\r\n'
    b'        ("ict_elv",            "Cat6 UTP Data Outlet (RJ45)",          "Legrand",   "RJ45-C6",    "Cat6 UTP RJ45 data outlet, flush, white",            "No.",     8, rs,        7,  "Data Outlets"),\r\n'
    b'        ("ict_elv",            "24-port Gigabit PoE+ Switch",          "Cisco",     "CBS250-24P", "24-port Gigabit + 4 SFP, PoE+ 195W, managed",        "No.",   620, rs,        21, "Network Switches"),\r\n'
    b'        ("ict_elv",            "4MP IP Bullet CCTV Camera",            "Hikvision", "DS-2CD2043", "4MP IR fixed bullet, IP67, PoE, 2.8mm lens",         "No.",    95, rs,        14, "CCTV"),\r\n'
    b'        ("ict_elv",            "Addressable Smoke Detector",           "Honeywell", "SD-ADR-100", "Photoelectric addressable smoke detector, EN54-7",   "No.",    52, rs,        14, "Fire Alarm"),\r\n'
    b'    ]\r\n'
    b'    # Build a code \xe2\x86\x92 display-name map from the seed list so the legacy\r\n'
)
assert data.count(SQLITE_OLD) == 1, (
    f"Patch B anchor not unique or missing (count={data.count(SQLITE_OLD)})"
)
data = data.replace(SQLITE_OLD, SQLITE_NEW)

# -- Patch C: extend Postgres suppliers list ----------------------------------
PG_SUP_OLD = (
    b'            ("ABB",     "Sweden",  "sales@abb.com",      "Transformers,Switchgear"),\r\n'
    b'        ]:\r\n'
)
PG_SUP_NEW = (
    b'            ("ABB",     "Sweden",  "sales@abb.com",      "Transformers,Switchgear"),\r\n'
    b'            ("Eaton",   "USA",     "sales@eaton.com",    "Switchgear,UPS,Panels"),\r\n'
    b'            ("Hager",   "Germany", "sales@hager.com",    "DBs,Consumer Units"),\r\n'
    b'            ("Legrand", "France",  "sales@legrand.com",  "Sockets,Switches,ICT"),\r\n'
    b'            ("Siemens", "Germany", "sales@siemens.com",  "Switchgear,Drives,Transformers"),\r\n'
    b'            ("Polycab", "India",   "sales@polycab.com",  "Cables,Wires"),\r\n'
    b'            ("RR Kabel","India",   "sales@rrkabel.com",  "Wires,Fire-resistant"),\r\n'
    b'            ("JA Solar","China",   "sales@jasolar.com",  "PV Modules"),\r\n'
    b'            ("Victron", "Netherlands","sales@victronenergy.com","Inverters,Solar"),\r\n'
    b'            ("Pylontech","China",  "sales@pylontech.com","Batteries"),\r\n'
    b'            ("Cummins", "USA",     "sales@cummins.com",  "Generators"),\r\n'
    b'            ("APC",     "USA",     "sales@apc.com",      "UPS"),\r\n'
    b'            ("Cisco",   "USA",     "sales@cisco.com",    "Network,ICT"),\r\n'
    b'            ("Hikvision","China",  "sales@hikvision.com","CCTV,Security"),\r\n'
    b'            ("Honeywell","USA",    "sales@honeywell.com","Fire Alarm,BMS"),\r\n'
    b'        ]:\r\n'
)
assert data.count(PG_SUP_OLD) == 1, (
    f"Patch C suppliers anchor not unique (count={data.count(PG_SUP_OLD)})"
)
data = data.replace(PG_SUP_OLD, PG_SUP_NEW)

# -- Patch D: extend Postgres seed samples (ASCII-only) -----------------------
PG_OLD = (
    b'        ("light_switches",     "3 Gang 2 Way Switch",                  "MK",        "K4873WHI",   "3 gang 2 way switch, 10A, white",                    "No.",    11, mk,        7,  "3 Gang 2 Way"),\r\n'
    b'    ]\r\n'
    b'    code_to_label = {row[0]: row[1] for row in _MARKETPLACE_CATEGORIES}\r\n'
    b'    with get_db() as c:\r\n'
)
PG_NEW = (
    b'        ("light_switches",     "3 Gang 2 Way Switch",                  "MK",        "K4873WHI",   "3 gang 2 way switch, 10A, white",                    "No.",    11, mk,        7,  "3 Gang 2 Way"),\r\n'
    b'        # - Extra coverage (ASCII-only spec text for safe Postgres write) -----\r\n'
    b'        ("transformers",       "Schneider 100 kVA Dry Type",           "Schneider", "DT100",      "100 kVA, 11/0.4 kV, AN, IP00, IEC 60076-11",         "No.",  4200, schneider, 60, "Dry Type"),\r\n'
    b'        ("transformers",       "ABB 1000 kVA Package Substation",      "ABB",       "PSS-1000",   "1000 kVA, 11/0.4 kV, ONAN, Dyn11, packaged unit",    "No.", 18500, abb,       75, "Package Substation"),\r\n'
    b'        ("avr",                "Static AVR 10 kVA 1-Phase",            "Generic",   "SAVR-10K-1P", "10 kVA, 1PH, Static IGBT, +/-3% accuracy",          "No.",   620, generic,   14, "Single-phase"),\r\n'
    b'        ("hv_cables",          "33 kV XLPE 1C 240mm2 Cu Armoured",     "Nexans",    "HV-33-1C240","33 kV, XLPE/CWS/PVC, Copper, 1 core, 240mm2",        "m",     145, nexans,    45, "1C HV Armoured"),\r\n'
    b'        ("hv_cables",          "11 kV 3C 95mm2 Al Armoured",           "Nexans",    "HV-11-3C95A","11 kV, XLPE/SWA/PVC, Aluminium, 3 core, 95mm2",      "m",      38, nexans,    45, "Aluminium HV"),\r\n'
    b'        ("lv_cables",          "LV 2C 4mm2 Cu PVC/SWA/PVC",            "Nexans",    "LV-2C-4P",   "0.6/1 kV, 2 core, 4mm2, Cu, PVC/SWA/PVC",            "m",       6, nexans,    14, "PVC/SWA/PVC"),\r\n'
    b'        ("lv_cables",          "LV 3C 6mm2 Cu Flex H07RN-F",           "Nexans",    "FLX-3C-6",   "450/750 V, 3 core, 6mm2, Cu, rubber-sheathed",       "m",       8, nexans,    14, "Flexible Power"),\r\n'
    b'        ("wires",              "Earth Wire 6mm2 Green/Yellow (100m)",  "Polycab",   "EW-6-GY",    "6mm2 Cu, 450/750 V, PVC, green/yellow",              "Roll",   48, generic,   7,  "Earth Wire"),\r\n'
    b'        ("wires",              "Fire-resistant 1.5mm2 (100m)",         "RR Kabel",  "FR-1.5",     "1.5mm2 Cu, FR-LSZH, 450/750 V, red",                 "Roll",   58, generic,   14, "Fire-resistant"),\r\n'
    b'        ("panel_boards",       "1000A ATS Panel",                      "Schneider", "ATS-1000",   "1000A 3PH ATS, AMF + utility/genset, IP54",          "No.", 14500, schneider, 60, "ATS Panel"),\r\n'
    b'        ("panel_boards",       "200kVAr PFC Panel",                    "Schneider", "PFC-200",    "200 kVAr, 10 stages, contactor-switched, IP42",      "No.",  6200, schneider, 45, "PFC Panel"),\r\n'
    b'        ("distribution_boards","12-way Metal Clad TPN DB",             "Hager",     "DB-12MCTPN", "12-way TPN MC, 125A incomer, 10kA, IP54",            "No.",   320, schneider, 21, "Metal Clad"),\r\n'
    b'        ("distribution_boards","6-way Flush Consumer Unit",            "Hager",     "DB-6FCU",    "6-way SPN flush, 63A RCD + 6 MCBs",                  "No.",   135, schneider, 14, "Flush Mounted"),\r\n'
    b'        ("isolators",          "32A 2-Pole AC Isolator IP65",          "Schneider", "ISO-32-2P",  "32A 2P AC isolator, IP65, weatherproof",             "No.",    24, schneider, 14, "Double-pole"),\r\n'
    b'        ("isolators",          "16A 4-Pole DC Isolator (Solar)",       "Schneider", "ISO-16-DC",  "16A 4P DC isolator, 1000 VDC, IP65, lockable",       "No.",    42, schneider, 21, "DC"),\r\n'
    b'        ("fuse_switches",      "200A Fuse Switch Disconnector",        "ABB",       "FSD-200",    "200A 4P FSD, 50kA, HRC fuses, IP30",                 "No.",   245, abb,       21, "Fuse Switch Disconnector"),\r\n'
    b'        ("fuse_switches",      "400A Changeover Fuse Switch",          "ABB",       "CFS-400",    "400A 4P changeover, manual, IP31",                   "No.",   485, abb,       30, "Changeover"),\r\n'
    b'        ("conduit",            "GI Conduit 20mm (3m)",                 "Generic",   "GI-20",      "20mm dia hot-dip galv steel conduit, 3m, class 4",   "m",       2, generic,   7,  "GI"),\r\n'
    b'        ("conduit",            "Flexible Metallic 25mm (per m)",       "Generic",   "FLX-25M",    "25mm dia flexible metallic conduit, PVC-coated",     "m",       3, generic,   7,  "Flexible"),\r\n'
    b'        ("steel_boxes",        "3 Gang Surface Steel Box",             "Generic",   "SB-3G-S",    "3 gang surface flush steel back box, 35mm deep",     "No.",     5, generic,   7,  "3 Gang"),\r\n'
    b'        ("steel_boxes",        "4 Gang Deep Steel Box",                "Generic",   "SB-4G-D",    "4 gang deep flush steel back box, 50mm deep",        "No.",     6, generic,   7,  "4 Gang"),\r\n'
    b'        ("circular_boxes",     "PVC Junction Box 80mm IP65",           "Generic",   "JB-PVC-80",  "80mm PVC junction box, 4 knockouts, IP65",           "No.",     3, generic,   7,  "Junction"),\r\n'
    b'        ("cable_trays",        "Ladder Tray 450mm (3m) HDG",           "Generic",   "LT-450",     "450mm wide ladder cable tray, HDG, 3m length",       "m",      32, generic,   21, "Ladder"),\r\n'
    b'        ("cable_trays",        "Wire Mesh Tray 200mm (3m)",            "Generic",   "WMT-200",    "200mm wide wire-mesh basket tray, EZ, 3m",           "m",      14, generic,   14, "Wire Mesh"),\r\n'
    b'        ("trunking",           "Dado Trunking 100x50mm (2m)",          "Generic",   "DT-100-50",  "100x50mm dado trunking, 2 compartments, white",      "m",      18, generic,   14, "Dado"),\r\n'
    b'        ("trunking",           "Skirting Trunking 75x18mm (2m)",       "Generic",   "ST-75-18",   "75x18mm skirting trunking, white",                   "m",       8, generic,   7,  "Skirting"),\r\n'
    b'        ("earthing",           "Earth Rod 16mm x 1.2m Cu-bonded",      "Generic",   "ER-16-1.2",  "16mm x 1.2m Cu-bonded steel earth rod with clamp",   "No.",    18, generic,   7,  "Earth Rods"),\r\n'
    b'        ("earthing",           "Copper Tape 25x3mm (10m roll)",        "Generic",   "CT-25-3",    "25x3mm bare Cu tape, 10m roll, lightning protection","Roll",   95, generic,   14, "Copper Tape"),\r\n'
    b'        ("earthing",           "Exothermic Weld Kit (Cu/Cu Tee)",      "Generic",   "EXO-CC-T",   "Exothermic weld kit, Cu/Cu tee, 95mm2",              "No.",    32, generic,   14, "Exothermic Kits"),\r\n'
    b'        ("sockets",            "13A IP66 Weatherproof Twin Socket",    "MK",        "K56480WHI",  "13A twin switched, IP66, surface, grey",             "No.",    28, mk,        14, "Weatherproof"),\r\n'
    b'        ("sockets",            "13A Metal Clad Twin Socket",           "MK",        "K2747ALM",   "13A twin switched, metal-clad, surface",             "No.",    22, mk,        14, "Metal Clad"),\r\n'
    b'        ("dp_switches",        "20A DP AC Switch with Neon",           "MK",        "K5423WHI",   "20A DP switch with neon, flush, for AC, white",      "No.",    13, mk,        7,  "Air Conditioner"),\r\n'
    b'        ("dp_switches",        "20A Metal Clad DP Switch",             "MK",        "K5403ALM",   "20A DP switch, metal-clad surface, IP2X",            "No.",    16, mk,        14, "Metal Clad"),\r\n'
    b'        ("light_switches",     "1 Gang 1 Way Switch",                  "MK",        "K4870WHI",   "1 gang 1 way switch, 10A, white",                    "No.",     5, mk,        7,  "1 Gang 1 Way"),\r\n'
    b'        ("light_switches",     "4 Gang 2 Way Switch",                  "MK",        "K4874WHI",   "4 gang 2 way switch, 10A, white",                    "No.",    14, mk,        7,  "4 Gang"),\r\n'
    b'        ("light_switches",     "Intermediate Switch 1G",               "MK",        "K4875WHI",   "1 gang intermediate switch, 10A, white",             "No.",     9, mk,        7,  "Intermediate"),\r\n'
    b'        ("light_switches",     "Dimmer Switch 1G 400W",                "MK",        "K1500WHI",   "1 gang push-rotary dimmer, 60-400W, white",          "No.",    18, mk,        7,  "Dimmer"),\r\n'
    b'        ("solar_equipment",    "JA Solar 550W Mono PV Module",         "JA Solar",  "JAM72S30-550","550W, mono-PERC, 72-cell, 21.3% eff., 12-yr product","No.",   180, sup.get("JA Solar", generic), 21, "PV Modules"),\r\n'
    b'        ("solar_equipment",    "Victron MultiPlus-II 5kVA Inverter",   "Victron",   "PMP482505010","5 kVA hybrid, 48V, 70A charger, parallel-stackable",  "No.",  1480, sup.get("Victron", generic), 14, "Hybrid Inverters"),\r\n'
    b'        ("solar_equipment",    "Pylontech US5000 4.8kWh LFP Battery",  "Pylontech", "US5000",     "4.8 kWh, 48V, LFP, 6000 cycles @ 80% DoD",           "No.",  1380, sup.get("Pylontech", generic), 21, "Batteries"),\r\n'
    b'        ("solar_equipment",    "MC4 Connector Pair (TUV)",             "Generic",   "MC4-PAIR",   "MC4 male+female connector pair, TUV, 1500 VDC",      "No.",     2, generic,   7,  "MC4 Connectors"),\r\n'
    b'        ("solar_equipment",    "DC Combiner Box 4-in/1-out 1000V",     "Generic",   "DCB-4-1",    "4-in/1-out DC combiner, 1000 VDC, SPD + fuses, IP65","No.",   145, generic,   14, "Combiner Boxes"),\r\n'
    b'        ("power_system",       "11 kV RMU 2-Way Compact",              "ABB",       "SafeRing-2W","11 kV, 2-way ring main unit, SF6, 630A, 21kA",       "No.", 11500, abb,       75, "RMU"),\r\n'
    b'        ("power_system",       "250 kVA Cummins Genset",               "Cummins",   "C250D5",     "250 kVA, 3PH, diesel, open-set, 1500 rpm",           "No.", 28500, sup.get("Cummins", generic), 45, "Generators"),\r\n'
    b'        ("power_system",       "10 kVA Online UPS Tower",              "APC",       "SRT10KXLI",  "10 kVA / 10 kW, online double-conversion, tower",    "No.",  4600, sup.get("APC", generic), 21, "UPS"),\r\n'
    b'        ("power_system",       "MCCB 400A 4P 50kA",                    "Schneider", "MCCB-400-4P","400A 4P MCCB, 50kA breaking capacity",               "No.",   520, schneider, 21, "Switchgear"),\r\n'
    b'        ("ict_elv",            "Cat6 UTP Data Outlet (RJ45)",          "Legrand",   "RJ45-C6",    "Cat6 UTP RJ45 data outlet, flush, white",            "No.",     8, sup.get("Legrand", generic), 7,  "Data Outlets"),\r\n'
    b'        ("ict_elv",            "24-port Gigabit PoE+ Switch",          "Cisco",     "CBS250-24P", "24-port Gigabit + 4 SFP, PoE+ 195W, managed",        "No.",   620, sup.get("Cisco", generic), 21, "Network Switches"),\r\n'
    b'        ("ict_elv",            "4MP IP Bullet CCTV Camera",            "Hikvision", "DS-2CD2043", "4MP IR fixed bullet, IP67, PoE, 2.8mm lens",         "No.",    95, sup.get("Hikvision", generic), 14, "CCTV"),\r\n'
    b'        ("ict_elv",            "Addressable Smoke Detector",           "Honeywell", "SD-ADR-100", "Photoelectric addressable smoke detector, EN54-7",   "No.",    52, sup.get("Honeywell", generic), 14, "Fire Alarm"),\r\n'
    b'    ]\r\n'
    b'    code_to_label = {row[0]: row[1] for row in _MARKETPLACE_CATEGORIES}\r\n'
    b'    with get_db() as c:\r\n'
)
assert data.count(PG_OLD) == 1, (
    f"Patch D Postgres seed anchor not unique (count={data.count(PG_OLD)})"
)
data = data.replace(PG_OLD, PG_NEW)

TARGET.write_bytes(data)
print(f"OK -- patched web_app.py ({TARGET.stat().st_size:,} bytes)")
