"""Byte-replace rename of display text in calculation/ modules: Solar PV -> PV Solar.

Sister to scripts/patch_solar_to_pv_rename.py (which targets web_app.py).
Same approach: narrow phrase-specific byte substitutions with asserted
expected-occurrence counts. Idempotent (re-running fails fast).

Tool-name lines use the compound form per the rename plan:
    "SolarPro Design" -> "SolarPro Design — PV Solar Designer Lite"
"""
from __future__ import annotations
import sys
import py_compile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CALC = ROOT / "calculation"

EMDASH = b"\xe2\x80\x94"
COMPOUND = b"SolarPro Design " + EMDASH + b" PV Solar Designer Lite"

# Per-file edits. Needles must be unique within each file.
FILES: dict[str, list[tuple[bytes, int, bytes, str]]] = {
    "boq_generator.py": [
        (b"Solar PV Modules (400 Wp each)", 1,
         b"PV Solar Modules (400 Wp each)",
         "line ~75: BoQ row label"),
        (b"Project  : Solar PV Off-Grid System", 1,
         b"Project  : PV Solar Off-Grid System",
         "line ~105: BoQ header"),
    ],
    "specification_generator.py": [
        (b"Project  : Solar PV Off-Grid System", 1,
         b"Project  : PV Solar Off-Grid System",
         "line ~22: spec header"),
        (b"Prepared : SolarPro Design", 1,
         b"Prepared : " + COMPOUND,
         "line ~25: spec tool-name (compound)"),
    ],
    "economic_impact_generator.py": [
        (b"  Project  : Solar PV Off-Grid System", 1,
         b"  Project  : PV Solar Off-Grid System",
         "line ~342: txt header"),
        (b"  Tool     : SolarPro Design", 1,
         b"  Tool     : " + COMPOUND,
         "line ~345: txt tool-name (compound)"),
        (b"Tool: SolarPro Design", 1,
         b"Tool: " + COMPOUND,
         "line ~607: HTML tool-name (compound)"),
        (b"SolarPro Design &nbsp;|&nbsp; Ghana", 1,
         COMPOUND + b" &nbsp;|&nbsp; Ghana",
         "line ~750: HTML footer tool-name (compound)"),
    ],
    "installation_method_generator.py": [
        (b'"  Solar PV Off-Grid System",', 1,
         b'"  PV Solar Off-Grid System",',
         "line ~57: header sub-line"),
        (b"Project   : Solar PV Off-Grid System", 1,
         b"Project   : PV Solar Off-Grid System",
         "line ~59: header Project line (3 spaces)"),
        (b" " + EMDASH + b" SOLAR PV MODULES", 2,
         b" " + EMDASH + b" PV SOLAR MODULES",
         "lines ~257 + ~261: ITEM 1 comment + display header"),
        (b"off-grid solar PV system " + EMDASH + b" from the PV array", 1,
         b"off-grid pv solar system " + EMDASH + b" from the PV array",
         "line ~1374: HTML prose (lowercase to match web_app.py pattern)"),
        (b"Item 1 " + EMDASH + b" Solar PV Modules", 1,
         b"Item 1 " + EMDASH + b" PV Solar Modules",
         "line ~1410: section() title"),
        (b"off-grid / hybrid solar PV system", 1,
         b"off-grid / hybrid pv solar system",
         "line ~1592: HTML prose (lowercase)"),
        (b"Installation Method Report " + EMDASH + b" Solar PV Off-Grid System", 1,
         b"Installation Method Report " + EMDASH + b" PV Solar Off-Grid System",
         "line ~1648: <title>"),
        (b"Solar PV Off-Grid System &nbsp;|&nbsp; {region_name}", 1,
         b"PV Solar Off-Grid System &nbsp;|&nbsp; {region_name}",
         "line ~1655: HTML header meta"),
        (b"Generated by SolarPro Design &nbsp;", 1,
         b"Generated by " + COMPOUND + b" &nbsp;",
         "line ~1675: HTML footer (compound)"),
    ],
}


def _safe(b: bytes, n: int = 60) -> str:
    return b[:n].decode("utf-8", errors="replace")


def main() -> int:
    total = 0
    for fname, edits in FILES.items():
        target = CALC / fname
        if not target.exists():
            sys.exit(f"target not found: {target}")
        data = target.read_bytes()
        orig_len = len(data)

        # Idempotency check: if NO needles match AND all replacements are present,
        # treat as already-applied and skip.
        all_needles_zero = all(data.count(n) == 0 for n, _, _, _ in edits)
        all_repls_present = all(data.count(r) >= 1 for _, _, r, _ in edits)
        if all_needles_zero and all_repls_present:
            print(f"{fname}: already applied, skipping")
            continue

        print(f"\n{fname}: {orig_len:,} bytes, {len(edits)} edits")
        new_data = data
        for needle, expected, replacement, why in edits:
            got = new_data.count(needle)
            if got != expected:
                sys.exit(
                    f"abort: {fname}: needle {_safe(needle)!r} found {got}x, expected {expected}\n"
                    f"  context: {why}"
                )
            before = new_data
            new_data = new_data.replace(needle, replacement)
            assert before != new_data, f"replace no-op for {_safe(needle)!r}"
            print(f"  ok: {got}x  {_safe(needle):60s} ({why})")
            total += got

        if new_data == data:
            sys.exit(f"nothing changed for {fname} - aborting")
        target.write_bytes(new_data)
        print(f"  wrote {fname}: {len(new_data):,} bytes (delta {len(new_data)-orig_len:+d})")

        try:
            py_compile.compile(str(target), doraise=True)
            print(f"  py_compile OK")
        except py_compile.PyCompileError as e:
            sys.exit(f"py_compile FAILED post-edit on {fname}:\n{e}")

    print(f"\nDone. {total} replacements this run.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
